# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "story" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI, ie.: "New Post"
    folder: "_news" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Outcasts Admin", value: "outcasts_admin" }
          - { label: "Dickon Tolson", value: "dickon_tolson" }
          - { label: "Lance Steen Anthony Nielsen", value: "lance" }
          - { label: "Suzette Pluck", value: "suzette_pluck" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
  # PRODUCTIONS
  - name: "production" # Used in routes, ie.: /admin/productions/:slug/edit
    label: "Productions" # Used in the UI, ie.: "New Production"
    folder: "_production" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    # CLASSES
  - name: "class" # Used in routes, ie.: /admin/productions/:slug/edit
    label: "Classes" # Used in the UI, ie.: "New Production"
    folder: "_class" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
